# Generated by Django 3.1.2 on 2021-08-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210616_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('M', 'Meeting'), ('A', 'Appointment')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
