# Generated by Django 3.1.2 on 2021-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Visible to Public'),
        ),
    ]
