# Generated by Django 3.1.2 on 2021-08-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20210804_2011'),
        ('forum', '0004_auto_20210630_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlagPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.BooleanField(default=False)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberuser')),
            ],
        ),
    ]
