# Generated by Django 3.1.2 on 2021-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_userflagpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='flageged',
            field=models.BooleanField(default=False),
        ),
    ]
