# Generated by Django 3.1.2 on 2021-08-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_discussion_flageged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='flageged',
            new_name='flagged',
        ),
    ]
