# Generated by Django 3.1.2 on 2021-08-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210804_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
