# Generated by Django 3.1.2 on 2021-08-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_userflagcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
