# Generated by Django 3.1.2 on 2021-07-14 20:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_permissions_can_add_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_file')),
            ],
            options={
                'verbose_name': 'Application Upload',
                'verbose_name_plural': 'Application Uploads',
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='org_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='org_name',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='birthdate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='business_website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City/Town'),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='other',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='Test', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='referred_by',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='surname',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
