# Generated by Django 3.1.2 on 2021-07-21 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20210721_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationupload',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 13, 29, 25, 889323)),
        ),
        migrations.AddField(
            model_name='applicationupload',
            name='processsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 21, 13, 29, 25, 888715)),
        ),
    ]
