# Generated by Django 3.1.2 on 2021-08-04 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20210804_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number_of_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberuser',
            name='number_of_flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 19, 36, 17, 700147)),
        ),
        migrations.AlterField(
            model_name='applicationupload',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 19, 36, 17, 701139)),
        ),
    ]
