# Generated by Django 3.1.2 on 2021-08-30 15:00

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20210805_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 0, 37, 359681)),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email(*)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name(*)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CA', verbose_name='Phone Number(*)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Last Name(*)'),
        ),
        migrations.AlterField(
            model_name='applicationupload',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 0, 37, 360381)),
        ),
    ]
