# Generated by Django 3.1.2 on 2021-08-30 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_auto_20210830_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 4, 29, 405484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicationupload',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 15, 4, 29, 406126, tzinfo=utc)),
        ),
    ]
