# Generated by Django 3.1.2 on 2021-08-30 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20210830_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='applicationupload',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
